bk/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "bk"

urlpatterns = [
    #url(r'^$',views.Index.index , name="index" ),
    url(r'^$',views.Mainpage.mainpage,name="mainpage"),
    url(r'^n21/$',views.N21.n21 , name="n21" ),
    url(r'^ajax_n21_gettimes/$', views.N21.ajax_n21_gettimes, name="ajax_n21_gettimes"),
    url(r'^ajax_n21_getquestion/$',views.N21.ajax_n21_getquestion,name="ajax_n21_getquestion"),

    url(r'^n22/$', views.N22.n22, name="n22"),
    url(r'^ajax_n22_gettimes/$', views.N22.ajax_n22_gettimes, name="ajax_n22_gettimes"),
    url(r'^ajax_n22_getquestion/$', views.N22.ajax_n22_getquestion, name="ajax_n22_getquestion"),

    url(r'^n23/$', views.N23.n23, name="n23"),
    url(r'^ajax_n23_gettimes/$', views.N23.ajax_n23_gettimes, name="ajax_n23_gettimes"),
    url(r'^ajax_n23_getquestion/$', views.N23.ajax_n23_getquestion, name="ajax_n23_getquestion"),

    url(r'^n24/$', views.N24.n24, name="n24"),
    url(r'^ajax_n24_gettimes/$', views.N24.ajax_n24_gettimes, name="ajax_n24_gettimes"),
    url(r'^ajax_n24_getquestion/$', views.N24.ajax_n24_getquestion, name="ajax_n24_getquestion"),

    url(r'^n25/$', views.N25.n25, name="n25"),
    url(r'^ajax_n25_gettimes/$', views.N25.ajax_n25_gettimes, name="ajax_n25_gettimes"),
    url(r'^ajax_n25_getquestion/$', views.N25.ajax_n25_getquestion, name="ajax_n25_getquestion"),

    url(r'^n21cbt/$', views.N21CBT.n21cbt, name="n21cbt"),
    url(r'^ajax_n21cbt_gettimes/$', views.N21CBT.ajax_n21cbt_gettimes, name="ajax_n21cbt_gettimes"),
    url(r'^ajax_n21cbt_getquestion/$', views.N21CBT.ajax_n21cbt_getquestion, name="ajax_n21cbt_getquestion"),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

exam/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "exam"

urlpatterns = [
    url(r'^$',views.Index.index , name="index" ),
    url(r'^admin/',admin.site.urls),
    #MainPage メインページ
    url(r'^mainpage/$', views.MainPage.mainpage, name='mainpage'),
    # Addlicense
    url(r'^addlicense/$', views.Addlicense.addlicense, name='addlicense'),
    # AddlicenseConf
    url(r'^addlicense_conf/$', views.AddlicenseConf.addlicense_conf, name='addlicense_conf'),
    # Inquiry
    url(r'^inquiry/$', views.Inquiry.inquiry, name='inquiry'),
    # Logoff
    url(r'^logoff/$',views.Logoff.logoff,name="logoff"),
    # NewUser
    url(r'^newuser/$', views.NewUser.newuser, name='newuser'),
    # OrgRegister
    url(r'^orgregister/$',views.OrgRegister.orgregister,name='orgregister'),
    # PassChange
    url(r'^passchange/$',views.PassChange.passchange,name='passchange'),
    # PassChangeFinish
    url(r'^passchange_finish',views.PassChangeFinish.passchange_finish,name='passchange_finish'),
    # UserRegisterCsv
    url(r'^userregistercsv/$', views.UserRegisterCsv.userregistercsv, name='userregistercsv'),
    # UserRegisterWeb
    url(r'^userregisterweb/$', views.UserRegisterWeb.userregisterweb, name='userregisterweb'),
    # SaLogin
    url(r'^salogin/$',views.SaLogin.salogin,name='salogin'),
    # SaPage
    url(r'^sapage/$',views.SaPage.sapage,name='sapage'),
    # SaAddlicense
    url(r'^saaddlicense/$',views.SaAddlicense.saaddlicense,name='saaddlicense'),
    # SaAddlicenseFilter
    url(r'^saaddlicense_filter/$',views.SaAddlicenseFilter.saaddlicense_filter,name='saaddlicense_filter'),
    #SaAddlicenseConf
    url(r'^saaddlicense_conf/$',views.SaAddlicenseConf.saaddlicense_conf,name='saaddlicense_conf'),
    # QuestionAmUpLoad
    url(r'^question_am_upload/$',views.QuestioinAmUpload.question_am_upload,name='question_am_upload'),

]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

examsite/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^exam/',include( 'exam.urls')),
    url(r'^jg/', include('jg.urls')),
    url(r'^bk/', include('bk.urls')),
    url(r'^jk/', include('jk.urls')),
    url(r'^ip/',include('ip.urls')),
    url(r'^manager/',include('manager.urls')),
]

ip/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "ip"

urlpatterns = [
    url(r'^mainpage/$', views.MainPage.mainpage, name="mainpage"),
    url(r'^ip_field/$',views.Ip_Field.ip_field,name="ip_field"),
    url(r'^ajax_ip_l_field_change/$',views.Ip_Field.ajax_ip_l_field_change,name="ajax_ip_l_field_change"),
    url(r'^ajax_ip_m_field_change/$',views.Ip_Field.ajax_ip_m_field_change,name="ajax_ip_m_field_change"),
    url(r'^ajax_ip_s_field_change/$',views.Ip_Field.ajax_ip_s_field_change,name="ajax_ip_s_field_change"),

]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

jg/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "jg"

urlpatterns = [
    #url(r'^$',views.Index.index , name="index" ),
    url(r'^mainpage/$',views.MainPage.mainpage,name="mainpage"),
    url(r'^mainpage_ajax_getperiod/$', views.MainPage.mainpage_ajax_getperiod, name='mainpage_ajax_getperiod'),
    url(r'^ajax_getquestion_period/$', views.MainPage.ajax_getquestion_period, name='ajax_getquestion_period'),
    url(r'^ajax_getquestion_classify/$', views.MainPage.ajax_getquestion_classify, name='ajax_getquestion_classify'),

    # TestMake　テストを作る
    url(r'^testmake/$', views.TestMake.testmake, name='testmake'),
    url(r'^ajax_getclass/$', views.TestMake.ajax_getclass, name='ajax_getclass'),
    url(r'^ajax_getquestion/$', views.TestMake.ajax_getquestion, name='ajax_getquestion'),
    url(r'^ajax_testupdate/$', views.TestMake.ajax_testupdate, name='ajax_testupdate'),

    # TestMakePeriod　年度期ごとにテストを作る
    url(r'^testmakeperiod/$', views.TestMakePeriod.testmakeperiod, name='testmakeperiod'),
    url(r'^ajax_getperiod/$', views.TestMakePeriod.ajax_getperiod, name='ajax_getperiod'),
    url(r'^ajax_testupdateperiod/$', views.TestMakePeriod.ajax_testupdateperiod, name='ajax_testupdateperiod'),

    # TestDelete テストを削除する
    url(r'^testdelete/$', views.TestDelete.testdelete, name='testdelete'),
    url(r'^ajax_testdelete/$', views.TestDelete.ajax_testdelete, name='ajax_testdelete'),

    # TestPrint　テストを印刷する
    url(r'^testprint/$', views.TestPrint.testprint, name='testprint'),
    url(r'^ajax_gettestprint/$', views.TestPrint.ajax_gettestprint, name='ajax_gettestprint'),

    # AnswerUpload 解答用紙アップロード
    url(r'^answerupload/$', views.AnswerUpload.answerupload, name='answerupload'),
    url(r'^ajax_answerupload/$', views.AnswerUpload.ajax_answerupload, name='ajax_answerupload'),
    url(r'^ajax_answerinsert/$', views.AnswerUpload.ajax_answerinsert, name='ajax_answerinsert'),
    url(r'^ajax_answerallinsert/$', views.AnswerUpload.ajax_answerallinsert, name='ajax_answerallinsert'),
    url(r'^ajax_getanswerlist/$', views.AnswerUpload.ajax_getanswerlist, name='ajax_getanswerlist'),

    # AnswerSheetPrint 解答用紙印刷
    url(r'^answersheetprint/$', views.AnswerSheetPrint.answersheetprint, name='answersheetprint'),
    url(r'^ajax_answersheetprint/$', views.AnswerSheetPrint.ajax_answersheetprint, name='ajax_answersheetprint'),

    # TrainPrint
    url(r'^trainprint/$', views.TrainPrint.trainprint, name='trainprint'),
    url(r'^ajax_gettrainprint/$', views.TrainPrint.ajax_gettrainprint, name='ajax_gettrainprint'),
    url(r'^ajax_testchange/$', views.TrainPrint.ajax_testchange, name='ajax_testchange'),
    url(r'^ajax_m_id_change/$', views.TrainPrint.ajax_m_id_change, name='ajax_m_id_change'),
    url(r'^ajax_s_id_change/$', views.TrainPrint.ajax_s_id_change, name='ajax_s_id_change'),
    url(r'^get_m_list', views.get_m_list, name='get_m_list'),
    url(r'^get_s_list', views.get_m_list, name='get_m_list'),

    # Analysis テストNOごとに結果分析
    url(r'^analysis', views.Analysis.analysis, name='analysis'),
    url(r'^ajax_gettid/$', views.Analysis.ajax_gettid, name='ajax_gettid'),
    url(r'^ajax_getresult/$', views.Analysis.ajax_getresult, name='ajax_getresult'),

    # A_Bunya　分野ごとのテスト結果
    url(r'^a_bunya', views.A_Bunya.a_bunya, name='a_bunya'),
    url(r'^ajax_getresultbunya/$', views.A_Bunya.ajax_getresultbunya, name='ajax_getresultbunya'),

    # A_All　すべてのテスト結果
    url(r'^a_all', views.A_All.a_all, name='a_all'),
    url(r'^ajax_gettestidlist', views.A_All.ajax_gettestidlist, name='ajax_gettestidlist'),
    url(r'^ajax_gettestidresult', views.A_All.ajax_gettestidresult, name='ajax_gettestidresult'),

    # Miss_Question　間違った問題のみ印刷
    url(r'^miss_question/$', views.Miss_Question.miss_question, name='miss_question'),
    url(r'^ajax_miss_question/$', views.Miss_Question.ajax_miss_question, name='ajax_miss_question'),

    # Question_Pm　午後問題
    url(r'^questionpm/$', views.Question_Pm.questionpm, name='questionpm'),
    url(r'^ajax_getquestionpm/$', views.Question_Pm.ajax_getquestionpm, name='ajax_questionpm'),

    # QuestionPmFrame
    url(r'^questionpmframe/$', views.QuestionPmFrame.questionpmframe, name='questionpmframe'),

    # cbt
    url(r'^cbtammain/$', views.CbtAmMain.cbtammain, name='cbtammain'),
    url(r'^cbtam/$', views.CbtAm.cbtam, name='cbtam'),
    url(r'^cbtamresult/$', views.CbtAmResult.cbtamresult, name='cbtamresult'),
    url(r'^cbtpmmain/$', views.CbtPmMain.cbtpmmain, name='cbtpmmain'),
    url(r'^cbtpm/$', views.CbtPm.cbtpm, name='cbtpm'),
    url(r'^cbtpmresult/$', views.CbtPmResult.cbtpmresult, name='cbtpmresult'),
    url(r'^cbtpmresultshow/$', views.CbtPmResultShow.cbtpmresultshow, name='cbtpmresultshow'),
    url(r'^ajax_cbtpm_delete/$',views.CbtPmResultShow.ajax_cbtpm_delete,name='ajax_cbtpm_delete'),
    url(r'^ajax_cbtpm_update/$', views.CbtPm.ajax_cbtpm_update, name='ajax_cbtpm_update'),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

jk/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "jk"

urlpatterns = [
    #url(r'^$',views.Index.index , name="index" ),
    # QuestionJs
    url(r'^questionjs/$', views.Question_Js.questionjs, name='questionjs'),
    url(r'^ajax_getquestionjs/$', views.Question_Js.ajax_getquestionjs, name='ajax_getquestionjs'),
    url(r'^ajax_gettitle/$', views.Question_Js.ajax_gettitle, name='ajax_gettitle'),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

exam/forms.py
from django import forms

class AnswerImageForm( forms.Form ):
    image = forms.ImageField()

exam/templates/exam/addlicense.html
{% extends 'base.html' %}

{% block title %}ライセンスの購入{% endblock %}

{% block bland %}ライセンスの購入{% endblock %}
{% block main %}
<div class="row">
    <div class="col-md-4">
        <p>組織ID：{{ o_id }}</p>
        <p>組織名:{{ o_name }}</p>
        <form action="{% url 'exam:addlicense_conf' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="o_id">組織ID：</label>
                <input type="text" class="form-control" id="o_id" name="o_id" value="{{ o_id }}">
                <label for="l_num">ライセンス数：</label>
                <input type="text" class="form-control" id="l_num" name="l_num">

            </div>
            <button type="submit" class="btn btn-primary" data-toggle="modal" data-target="#modal-progress">購入</button>
        </form>

    </div>
</div>
{% endblock %}

exam/templates/exam/errorpage.html
{% extends 'base.html' %}

{% block title %}エラーページ{% endblock %}

{% block main %}

{{ message }}
<p><a href="{% url 'exam:index' %}">戻る</a></p>

{% endblock %}

exam/templates/exam/index.html
{% extends 'base.html' %}

{% block title %}ログイン{% endblock %}

{% block nav %}{% endblock %}
{% block main %}
<div class="row">
    <div class="col-md-4">
<p>{{ message }}</p>
<form action="{% url 'exam:mainpage' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="u_id">UserId</label>
        <input type="text" class="form-control" id="u_id" placeholder="ユーザIDを入力してください。" name="u_id">
        <label for="u_pass">Password</label>
        <input type="password" class="form-control" id="u_pass" placeholder="Password" name="u_pass">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<p>新規ユーザ登録は<a href="{% url 'exam:newuser' %}">ここ</a>から</p>

<p>ユーザIDやパスワードを忘れた方は<a href="{% url 'exam:inquiry' %}">ここ</a>から</p>
</div>
</div>
{% endblock %}

exam/templates/exam/mainpage.html
{% extends 'base.html' %}

{% block title %}メッセージページ{% endblock %}
{% block css %}
span.answer{background-color : black;
color : black;
padding-left:50px;
padding-right:50px;}
span.answer:hover{background-color : white;}
p.question { margin-top : 30px; }
h2 {font-size : 15pt;}
h3 {font-size :12pt;}
{% endblock %}
{% load static %}
{% block main %}
<h1>メインページ</h1>
<div class="row">
    <div class="col">
        <p>{{ u_id }}:{{ u_name }}<a href="{% url 'exam:passchange' %}">パスワードの変更</a></p>
    </div>
</div>
<div class="row">
    <div class="list-group">
        <a href="{% url 'jg:mainpage' %}" class="list-group-item list-group-item-action">情報処理技術者試験</a>
        <a href="{% url 'jk:questionjs' %}" class="list-group-item list-group-item-action">情報システム試験</a>
        <a href="{% url 'bk:mainpage' %}" class="list-group-item list-group-item-action">簿記検定</a>
        <a href="{% url 'ip:mainpage' %}" class="list-group-item list-group-item-action">ITパスポート</a>
    </div>
</div>
{% csrf_token %}
{% endblock %}

exam/templates/exam/message.html
{% extends 'base.html' %}

{% block main %}

{{ message }}

{% endblock %}

exam/templates/exam/newuser.html
{% extends 'base.html' %}

{% block title %}新規ユーザ登録{% endblock %}

{% block header %}<h1>新規ユーザ登録</h1>{% endblock %}

{% block main %}
<p>{{ message }}</p>
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="e-mailを入力してください。" name="u_email">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<p>ログインページへ<a href="{% url 'exam:index' %}">戻る</a></p>
{% endblock %}

exam/templates/exam/orgregister.html
{% extends 'base.html' %}

{% block title %}ユーザ情報登録{% endblock %}

{% block container-header %}<h1>ユーザ情報登録</h1>{% endblock %}

{% block main %}
<p>{{ message }}</p>
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="u_id">User ID</label>
        <input type="text" class="form-control" id="u_id" placeholder="20文字以内でIDを決めてください。" name="u_id">

        <label for="u_pass">Password</label>
        <input type="password" class="form-control" id="u_pass" placeholder="20文字以内でパスワードを決めてください。" name="u_pass">

        <label for="u_name">管理者名</label>
        <input type="text" class="form-control" id="u_name" placeholder="管理者名（ユーザ名）を入力してください。" name="u_name">

        <label for="o_name">組織名</label>
        <input type="text" class="form-control" id="o_name" placeholder="組織名を入力してください。" name="o_name">

        <label for="u_email">登録したメールアドレスを入力してください</label>
        <input type="email" class="form-control" id="u_email" placeholder="メールアドレスを入力してください。" name="u_email">

        <input type="hidden" class="form_control" name="auth_key" value="{{ auth_key }}">

    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

exam/templates/exam/passchange.html
{% extends 'base.html' %}

{% block title %}パスワードの変更{% endblock %}
{% load static %}
{% block main %}
<div class="row">
    <div class="col-md-4">
        <p>{{ message }}</p>
        <form action="{% url 'exam:passchange_finish' %}" method="POST" id="p_form">
        {% csrf_token %}
            <div class="form-group">
                <label for="old_pass">古いパスワード：</label>
                <input type="password" class="form-control" id="old_pass" placeholder="古いパスワードの入力" name="old_pass">
                <label for="new_pass1">新しいパスワード</label>
                <input type="password" class="form-control" id="new_pass1" placeholder="Password" name="new_pass1">
                <label for="new_pass2">新しいパスワード</label>
                <input type="password" class="form-control" id="new_pass2" placeholder="もう一度入力してください。" name="new_pass2">

            </div>
            <button type="submit" class="btn btn-primary" id="submit">Submit</button>
        </form>

        <p>ユーザIDやパスワードを忘れた方は<a href="{% url 'exam:inquiry' %}">ここ</a>から</p>
        <p>変更せずに<a href="{% url 'exam:mainpage' %}">戻る</a></p>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'exam/js/passchange.js' %}" charset="utf-8"></script>
{% endblock %}

exam/templates/exam/question_am_upload.html
{% extends 'base.html' %}

{% load static %}
{% block title %}午前問題をアップロードする{% endblock %}
{% block header %}午前問題アップロード{% endblock %}

{% block main %}
<div class="row">
    <div class="col-md-5">
        <p>ファイル名ルール</p>
        <p>fer020101.png</p>
        <p>fe・・・基本情報　ap・・・応用情報</p>
        <p>r02・・・令和2年度</p>
        <p>01・・・春　02・・・秋</p>
        <p>01・・・問</p>
        <p id="msg"> {{ message }} </p>
        <!--解答ファイルをアップロードするフォーム-->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-group">
                <label class="input-group-btn">
                    <span class="btn btn-primary">
                        Choose File<input type="file" style="display:none" name="file" multiple accept="image/jpeg">
                    </span>
                </label>
                <input type="text" class="form-control" readonly="">

            </div>
            <input type="submit" value="upload" class="btn btn-primary">

        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-5">
        {% for file in filelist %}
            <p>{{ file }}</p>
        {% endfor %}
    </div>
</div>
<script type="text/javascript">

</script>
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'exam/js/question_am_upload.js' %}"></script>
{% endblock %}

exam/templates/exam/saaddlicense.html
{% extends 'exam/sapage.html' %}
{% load static %}
{% block main %}
<div class="row">
    <div class="col-md-3">
        <form>
            <div class="form-group">
                <select class="form-control" id="org">
                    <option></option>
                    {% for o in org_list %}
                        <option value="{{ o.o_id }}">{{ o.o_name }} , {{ o.l_num }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <button type="button" id="btn_per" class="form-control" data-toggle="modal" data-target="#modal-progress">認可</button>
            </div>
            <div class="form-group">
                <select class="form-control" id="id" size="10">
                    
                </select>
            </div>
        </form>
    </div>
</div>
{% csrf_token %}
<script type="text/javascript" src="{% static 'exam/js/saaddlicense.js' %}" charset="utf-8"></script>
{% endblock %}

exam/templates/exam/sapage.html
{% extends 'base.html' %}

{% block title %}サイト管理者ページ{% endblock %}

{% block nav%}
<div class="row">
        <div class="col-md-12">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">サイト管理者サイト</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="Navber">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'exam:sapage' %}">メインページ</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ライセンス</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'exam:saaddlicense' %}">ライセンス追加</a>
                            <a class="dropdown-item" href="#">ライセンス延長</a>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav my-2 my-lg-0">
                    <li class="nav-link">
                        <a class="nav-link" href="{% url 'exam:logoff' %}">ログオフ</a>
                    </li>
                </ul>
            </div>
        </nav>
        </div>
    </div>

{% endblock %}

{% block main %}

{% endblock %}

exam/templates/exam/test.html
{% extends 'base.html' %}

{% block addhead %}
<script type="text/javascript">
$(function(){
    $("#btn01").on("click",function(){
        btnOnClick();
    });
    function btnOnClick(){
        var name = $("#txtName").val();
        alert( name );
    }
});
</script>
{% endblock %}

{% block body %}
<select id="l_code">
    <option value="1"></option>
</select>
{% endblock %}

exam/templates/exam/userregisterweb.html
{% extends 'base.html' %}
{% block title %}ユーザ登録{% endblock %}
{% block header %}ユーザ登録{% endblock %}
{% block main %}
<form method="POST" action="{% url 'exam:userregisterweb' %}">
    {% csrf_token %}
    <div class="form-group">

        {% if u_id_error %}<strong class="error">{{ u_id_error }}</strong><br>{% endif %}
        <label for="u_id">ユーザID：</label>
        <input type="text" maxlength="8" name="u_id" id="u_id" class="form-control" placeholder="ユーザIDは20文字以内"><br>
    </div>
    <div class="form-group">
        {% if u_pass_error %}<strong class="error">{{ u_pass_error }}</strong><br>{% endif %}
        <label for="u_pass">ユーザパスワード：</label>
        <input type="text" maxlength="20" name="u_pass" id="u_pass" class="form-control" placeholder="パスワードは20文字以内"><br>
    </div>

    <div class="form-group">
        {% if u_name_error %}<strong class="error">{{ u_name_error }}</strong><br>{% endif %}
        <label for="u_name">ユーザ名：</label>
        <input type="text" maxlength="20" name="u_name" id="u_name" class="form-control" placeholder="フルネーム"><br>
    </div>
    <div class="form-group">
        {% if o_email_error %}<strong class="error">{{ o_email_error }}</strong><br>{% endif %}
        <label for="u_email">メールアドレス：</label>
        <input type="email" maxlength="100" name="u_email" id="u_email" class="form-control" placeholder="ユーザのE-mail">
    </div>
    <input type="submit" value="作成" class="btn btn-primary">

</form>
{% endblock %}