bk/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "bk"

urlpatterns = [
    #url(r'^$',views.Index.index , name="index" ),
    url(r'^$',views.Mainpage.mainpage,name="mainpage"),
    url(r'^n21/$',views.N21.n21 , name="n21" ),
    url(r'^ajax_n21_gettimes/$', views.N21.ajax_n21_gettimes, name="ajax_n21_gettimes"),
    url(r'^ajax_n21_getquestion/$',views.N21.ajax_n21_getquestion,name="ajax_n21_getquestion"),

    url(r'^n22/$', views.N22.n22, name="n22"),
    url(r'^ajax_n22_gettimes/$', views.N22.ajax_n22_gettimes, name="ajax_n22_gettimes"),
    url(r'^ajax_n22_getquestion/$', views.N22.ajax_n22_getquestion, name="ajax_n22_getquestion"),

    url(r'^n23/$', views.N23.n23, name="n23"),
    url(r'^ajax_n23_gettimes/$', views.N23.ajax_n23_gettimes, name="ajax_n23_gettimes"),
    url(r'^ajax_n23_getquestion/$', views.N23.ajax_n23_getquestion, name="ajax_n23_getquestion"),

    url(r'^n24/$', views.N24.n24, name="n24"),
    url(r'^ajax_n24_gettimes/$', views.N24.ajax_n24_gettimes, name="ajax_n24_gettimes"),
    url(r'^ajax_n24_getquestion/$', views.N24.ajax_n24_getquestion, name="ajax_n24_getquestion"),

    url(r'^n25/$', views.N25.n25, name="n25"),
    url(r'^ajax_n25_gettimes/$', views.N25.ajax_n25_gettimes, name="ajax_n25_gettimes"),
    url(r'^ajax_n25_getquestion/$', views.N25.ajax_n25_getquestion, name="ajax_n25_getquestion"),

    url(r'^n21cbt/$', views.N21CBT.n21cbt, name="n21cbt"),
    url(r'^ajax_n21cbt_gettimes/$', views.N21CBT.ajax_n21cbt_gettimes, name="ajax_n21cbt_gettimes"),
    url(r'^ajax_n21cbt_getquestion/$', views.N21CBT.ajax_n21cbt_getquestion, name="ajax_n21cbt_getquestion"),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

examsite/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^exam/',include( 'exam.urls')),
    url(r'^jg/', include('jg.urls')),
    url(r'^bk/', include('bk.urls')),
    url(r'^jk/', include('jk.urls')),
    url(r'^ip/',include('ip.urls')),
    url(r'^manager/',include('manager.urls')),
]

bk/views.py
from django.shortcuts import render
from exam.models import *
import json,ast
from django.http import HttpResponse
import re,string,random,datetime,os,csv
from django.conf import settings

#ajaxのPOSTデータをDictionaryに変換する
def byteToDic( data ):
    return ast.literal_eval( data.decode() )
#HttpResponseのJSON
def HttpResponseJson( jsonobj ):
    jsonStr = json.dumps( jsonobj , ensure_ascii=False, indent=2)
    return HttpResponse(jsonStr, content_type='application/json', charset='utf-8')

# 問題作成メイン画面
class Mainpage():
    def mainpage(request):

        return render( request,'bk/mainpage.html',{'u_admin':request.session['u_admin']})

#テスト印刷画面
class N21():
    #ページを表示する
    def n21( request ):
        user = request.session['u_id']
        o_id = request.session['o_id']

        field_list = []
        qb = QuestionBoki.objects.filter(b_que1='1').values('b_field').distinct()
        for q0 in qb:
            list = q0['b_field'].split(",")
            for q in list:
                field_list.append( q )

        return render( request,'bk/n21.html',{'field_list':set(field_list),'u_admin':request.session['u_admin']})

    #回を取得する
    def ajax_n21_gettimes(request):
        body = byteToDic( request.body )
        o_id = request.session['o_id']
        b_field = body['b_field']
        b_field2 = ""
        b_field3 = ""
        if 'b_field2' in body:
            b_field2 = body['b_field2']

        if 'b_field3' in body:
            b_field3 = body['b_field3']

        #print(b_field)

        if len( b_field3 ) > 0:
            qb = QuestionBoki.objects.filter(b_field__icontains=b_field,b_field2=b_field2,b_field3=b_field3,b_que1='1').values('b_field','b_field2','b_field3','b_times','b_que2','b_ocr').distinct().order_by('b_times').reverse()
        elif len( b_field2 ) > 0:
            qb = QuestionBoki.objects.filter(b_field__icontains=b_field,b_field2=b_field2,b_que1='1').values('b_field', 'b_field2','b_field3','b_times', 'b_que2','b_ocr').distinct().order_by('b_times').reverse()
        else:
            qb = QuestionBoki.objects.filter(b_field__icontains=b_field, b_que1='1').values('b_field', 'b_field2','b_field3','b_times', 'b_que2','b_ocr').distinct().order_by('b_times').reverse()

        #print( qb )
        data = {'qlist':[]}
        fields = []
        fields2 = []
        fields3 = []
        for q in qb:
            dic = {}
            dic['b_times'] = q['b_times']
            dic['b_que2'] = q['b_que2']
            dic['b_ocr'] = q['b_ocr'][0:100]
            data['qlist'].append( dic )
            for f in q['b_field'].split(','):
                fields.append( f )

            #print( q['b_field2'])
            if q['b_field2'] is not None:
                fields2.append( q['b_field2'])

            if q['b_field3'] is not None:
                fields3.append( q['b_field3'])

        data['field2'] = list(set(fields2))
        data['field3'] = list(set(fields3))
        #print( data )
        return HttpResponseJson( data )

    #テストの印刷用データをajaxで取得する
    def ajax_n21_getquestion( request ):
        body = byteToDic( request.body )
        o_id = request.session['o_id']
        b_times = body['b_times']
        #b_fields = body['b_field']
        data = {'qlist':[]}

        for b in b_times:
            bt = b.split("_")[0]
            bq2 = b.split("_")[2]

            q = QuestionBoki.objects.filter(b_times=bt,b_que1='1',b_que2=bq2).values().first()
            dic2 = {}
            dic2['b_id'] = q['b_id']
            dic2['b_times'] = q['b_times']
            dic2['b_que1'] = q['b_que1']
            dic2['b_que2'] = q['b_que2']
            dic2['b_field'] = q['b_field']
            #許容勘定科目
            b_fields = q['b_field']
            b_allow_field_list = []
            for b_field in b_fields.split(","):
                print( b_field )
                qbaf = QuestionBokiQ1AllowField.objects.filter(b_field=b_field).values().first()
                q1allow = qbaf['b_allow_field']
                print( q1allow )
                if q1allow is not None:
                    for qa in q1allow.split(','):
                        b_allow_field_list.append( qa )
            dic2['b_allow_field'] = list(set(b_allow_field_list))
            data['qlist'].append( dic2 )







        print( data )
        return HttpResponseJson( data )

#テスト印刷画面
class N22():
    #ページを表示する
    def n22( request ):
        user = request.session['u_id']
        o_id = request.session['o_id']

        field_list = []
        qb = QuestionBoki.objects.filter(b_que1='2').values('b_field').distinct()
        for q in qb:
            field_list.append( q['b_field'] )

        return render( request,'bk/n22.html',{'field_list':field_list,'u_admin':request.session['u_admin']})
    #回を取得する
    def ajax_n22_gettimes(request):
        body = byteToDic( request.body )
        o_id = request.session['o_id']
        b_field = body['b_field']
        qb = QuestionBoki.objects.filter(b_field=b_field,b_que1='2').values('b_times','b_ocr').distinct().order_by('b_times').reverse()
        print( qb )
        data = {'qlist':[]}
        for q in qb:
            dic = {}
            dic['b_times'] = q['b_times']
            dic['b_ocr'] = q['b_ocr'][0:100]
            data['qlist'].append( dic )

        print( data )
        return HttpResponseJson( data )

    #テストの印刷用データをajaxで取得する
    def ajax_n22_getquestion( request ):
        body = byteToDic( request.body )
        o_id = request.session['o_id']
        b_times = body['b_times']
        data = {'qlist':[]}
        for b in b_times:
            qb = QuestionBoki.objects.filter(b_times=b,b_que1='2').values()
            dic1 = {'b_times':b,'list':[]}
            for q in qb:
                dic2 = {}
                dic2['b_id'] = q['b_id']
                dic2['b_times'] = q['b_times']
                dic2['b_que1'] = q['b_que1']
                dic2['b_que2'] = q['b_que2']
                dic2['b_ans_page'] = q['b_ans_page']
                dic2['b_as_page'] = q['b_as_page']
                dic2['b_com_page'] = q['b_com_page']
                dic1['list'].append( dic2 )
            data['qlist'].append( dic1 )

        print( data )
        return HttpResponseJson( data )

#テスト印刷画面
class N23():
    #ページを表示する
    def n23( request ):
        user = request.session['u_id']
        o_id = request.session['o_id']

        field_list = []
        qb = QuestionBoki.objects.filter(b_que1='3').values('b_field').distinct()
        for q in qb:
            field_list.append( q['b_field'] )

        return render( request,'bk/n23.html',{'field_list':field_list,'u_admin':request.session['u_admin']})
    #回を取得する
    def ajax_n23_gettimes(request):
        body = byteToDic( request.body )
        o_id = request.session['o_id']
        b_field = body['b_field']
        print( b_field )
        qb = QuestionBoki.objects.filter(b_field=b_field,b_que1='3').values('b_times','b_ocr','b_que2').distinct().order_by('-b_times','b_que2')
        print( qb )
        data = {'qlist':[]}
        
        for q in qb:
            if q['b_que2'] == '1':
                dic = {}
                dic['b_times'] = q['b_times']
                dic['b_ocr'] = q['b_ocr'][0:100]
                data['qlist'].append( dic )

        print( data )
        return HttpResponseJson( data )

    #テストの印刷用データをajaxで取得する
    def ajax_n23_getquestion( request ):
        body = byteToDic( request.body )
        o_id = request.session['o_id']
        b_times = body['b_times']
        data = {'qlist':[]}
        for b in b_times:
            qb = QuestionBoki.objects.filter(b_times=b,b_que1='3').values()
            dic1 = {'b_times':b,'list':[]}
            for q in qb:
                dic2 = {}
                dic2['b_id'] = q['b_id']
                dic2['b_times'] = q['b_times']
                dic2['b_que1'] = q['b_que1']
                dic2['b_que2'] = q['b_que2']
                dic2['b_ans_page'] = q['b_ans_page']
                dic2['b_as_page'] = q['b_as_page']
                dic2['b_com_page'] = q['b_com_page']
                dic1['list'].append( dic2 )
            data['qlist'].append( dic1 )

        print( data )
        return HttpResponseJson( data )

#テスト印刷画面
class N24():
    #ページを表示する
    def n24( request ):
        user = request.session['u_id']
        o_id = request.session['o_id']

        field_list = []
        qb = QuestionBoki.objects.filter(b_que1='4').values('b_field').distinct()
        for q in qb:
            field_list.append( q['b_field'] )

        return render( request,'bk/n24.html',{'field_list':field_list,'u_admin':request.session['u_admin']})
    #回を取得する
    def ajax_n24_gettimes(request):
        body = byteToDic( request.body )
        o_id = request.session['o_id']
        b_field = body['b_field']
        qb = QuestionBoki.objects.filter(b_field=b_field,b_que1='4').values('b_times','b_ocr').distinct().order_by('b_times').reverse()
        print( qb )
        data = {'qlist':[]}
        for q in qb:
            dic = {}
            dic['b_times'] = q['b_times']
            dic['b_ocr'] = q['b_ocr'][0:100]
            data['qlist'].append( dic )

        print( data )
        return HttpResponseJson( data )

    #テストの印刷用データをajaxで取得する
    def ajax_n24_getquestion( request ):
        body = byteToDic( request.body )
        o_id = request.session['o_id']
        b_times = body['b_times']
        data = {'qlist':[]}
        for b in b_times:
            qb = QuestionBoki.objects.filter(b_times=b,b_que1='4').values()
            dic1 = {'b_times':b,'list':[]}
            for q in qb:
                dic2 = {}
                dic2['b_id'] = q['b_id']
                dic2['b_times'] = q['b_times']
                dic2['b_que1'] = q['b_que1']
                dic2['b_que2'] = q['b_que2']
                dic2['b_ans_page'] = q['b_ans_page']
                dic2['b_as_page'] = q['b_as_page']
                dic2['b_com_page'] = q['b_com_page']
                dic1['list'].append( dic2 )

bk/templates/bk/mainpage.html
{% extends 'bkbase.html' %}

{% block title %}メッセージページ{% endblock %}
{% block css %}
span.answer{background-color : black;
color : black;
padding-left:50px;
padding-right:50px;}
span.answer:hover{background-color : white;}
p.question { margin-top : 30px; }
h2 {font-size : 15pt;}
h3 {font-size :12pt;}
{% endblock %}
{% load static %}
{% block main %}

<div class="row" style="margin-top:20px">
    <div class="col-md-8">
        <!-- アコーディオンレベル１ -->
        <div class="accordion" id="accordion-1">
            <div class="card">
                <!-- アコーディオンレベル２ -->
                <div class="card-header" id="header-1">
                   <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#card-1" aria-expanded="true" aria-controls="card-1">日商簿記検定</button>
                </div>
                <div id="card-1" class="collapse" aria-labelledby="header-1" data-parent="#header-1">
                    <div class="card-body">
                        <!-- アコーディオンレベル３ -->
                        <div class="card-header" id="header-1-1">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#card-1-1" aria-expanded="true" aria-controls="card-1-1">２級</button>
                        </div>
                        <div id="card-1-1" class="collapse" aria-labelledby="header-1-1" data-parent="#header-1-1">
                            <div class="card-body"><a href="{% url 'bk:n21' %}">問１印刷ページ</a>,<a href="{% url 'bk:n21cbt' %}">問１Web試験ページ</a></div>
                            <div class="card-body"><a href="{% url 'bk:n22' %}">問２印刷ページ</a></div>
                            <div class="card-body"><a href="{% url 'bk:n23' %}">問３印刷ページ</a></div>
                            <div class="card-body"><a href="{% url 'bk:n24' %}">問４印刷ページ</a></div>
                            <div class="card-body"><a href="{% url 'bk:n25' %}">問５印刷ページ</a></div>
                        </div>
                        <!-- アコーディオンレベル３ -->
                        <div class="card-header" id="header-1-2">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#card-1-2" aria-expanded="true" aria-controls="card-1-2">３級</button>
                        </div>
                        <div id="card-1-2" class="collapse" aria-labelledby="header-1-2" data-parent="#header-1-2">
                            <div class="card-body">問１</div>
                            <div class="card-body">問２</div>
                            <div class="card-body">問３</div>
                            <div class="card-body">問４</div>
                            <div class="card-body">問５</div>
                        </div>
                    </div>
                </div>

                <!-- アコーディオンレベル２ -->
                <div class="card-header" id="header-2">
                   <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#card-2" aria-expanded="true" aria-controls="card-2">全経簿記検定</button>
                </div>
                <div id="card-2" class="collapse" aria-labelledby="header-2" data-parent="#header-2">
                    <div class="card-body">
                        <!-- アコーディオンレベル３ -->
                        <div class="card-header" id="header-2-1">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#card-2-1" aria-expanded="true" aria-controls="card-2-1">２級</button>
                        </div>
                        <div id="card-2-1" class="collapse" aria-labelledby="header-2-1" data-parent="#header-2-1">
                            <div class="card-body">問１</div>
                            <div class="card-body">問２</div>
                            <div class="card-body">問３</div>
                            <div class="card-body">問４</div>
                            <div class="card-body">問５</div>
                        </div>
                        <!-- アコーディオンレベル３ -->
                        <div class="card-header" id="header-2-2">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#card-2-2" aria-expanded="true" aria-controls="card-2-2">３級</button>
                        </div>
                        <div id="card-2-2" class="collapse" aria-labelledby="header-2-2" data-parent="#header-2-2">
                            <div class="card-body">問１</div>
                            <div class="card-body">問２</div>
                            <div class="card-body">問３</div>
                            <div class="card-body">問４</div>
                            <div class="card-body">問５</div>
                        </div>
                    </div>
                </div>
             </div>
        </div>

    </div>
    <div class="col-md-5">

    </div>
</div>
{% csrf_token %}
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'bk/js/mainpage.js' %}" charset="utf-8"></script>
{% endblock %}

bk/templates/bk/n21.html
{% extends 'bkbase.html' %}
{% load static %}

{% block addhead %}
<style type="text/css">
@media print{
    #header { display:none; }
}
</style>
{% endblock %}

{% block main %}
    <div id="header">
        <h1>日商簿記２級</h1>
        <div class="container-fluid">
            <div class="row" style="margin-top:20px;margin-bottom:20px">
                <div class="col-1"><a href="#" class="btn btn-success" role="button">問１</a></div>
                <div class="col-1"><a href="{% url 'bk:n22' %}" class="btn btn-primary" role="button">問２</a></div>
                <div class="col-1"><a href="{% url 'bk:n23' %}" class="btn btn-primary" role="button">問３</a></div>
                <div class="col-1"><a href="{% url 'bk:n24' %}" class="btn btn-primary" role="button">問４</a></div>
                <div class="col-1"><a href="{% url 'bk:n25' %}" class="btn btn-primary" role="button">問５</a></div>
        </div>
        </div>
        <div class="row">
            <div class="col">
                <form class="form-inline">
                    <div class="form-group">
                        分野1：
                        <select class="form-control d-print-none" id="s_test" style="width:150px;">
                            <option></option>
                            {% for field in field_list %}
                                <option value="{{ field }}">{{ field }}</option>
                            {% endfor %}
                        </select>
                        分野2：
                        <select class="form-control d-print-none" id="field2" style="width:150px;">
                            <option></option>
                        </select>
                        分野3：
                        <select class="form-control d-print-none" id="field3" style="width:150px;">
                            <option></option>
                        </select>
                    </div>

                    <div class="form-group">
                        <input type="button" class="form-contral" value="chkOn" id="chkon" style="margin-left:5px;">
                    </div>
                    <div class="form-group">
                        <input type="button" class="form-contral" value="chkOff" id="chkoff" style="margin-left:5px;">
                    </div>

                    <div class="form-group">
                        <input type="button" class="form-contral" value="印刷表示" id="print" style="margin-left:10px;">
                    </div>

                </form>

            </div>
        </div>
        <!-- 印刷リスト -->
        <div class="row" style="margin-top:10px;">
            <table id="printlist" class="table table-border">

            </table>
        </div>
    </div>

    <div class="row" style="margin-top:10px;">
        <div class="col">
            <p id="t_id"></p>
        </div>
    </div>
    <!--
    <p>許容勘定科目</p>
    <div class="row" style="border:1px solid black;padding:10px;font-size:18pt;">
        <table id="allow_field" style="width:800px;">

        </table>
    </div>
    -->
    <div class="row" style="margin-top:10px">
        <div id="qtable">

        </div>
    </div>
{% csrf_token %}
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'bk/js/n21.js' %}"></script>
{% endblock %}

bk/templates/bk/n22.html
{% extends 'bkbase.html' %}
{% load static %}

{% block addhead %}
<style type="text/css">
@media print{
    #header { display:none; }
}
</style>
{% endblock %}

{% block main %}
    <div id="header">
        <h1>日商簿記２級</h1>
        <div class="container-fluid">
            <div class="row" style="margin-top:20px;margin-bottom:20px">
                <div class="col-1"><a href="{% url 'bk:n21' %}" class="btn btn-primary" role="button">問１</a></div>
                <div class="col-1"><a href="#" class="btn btn-success" role="button">問２</a></div>
                <div class="col-1"><a href="{% url 'bk:n23' %}" class="btn btn-primary" role="button">問３</a></div>
                <div class="col-1"><a href="{% url 'bk:n24' %}" class="btn btn-primary" role="button">問４</a></div>
                <div class="col-1"><a href="{% url 'bk:n25' %}" class="btn btn-primary" role="button">問５</a></div>
        </div>
        </div>
        <div class="row">
            <div class="col">
                <form class="form-inline">
                    <div class="form-group">
                        分野選択：
                        <select class="form-control d-print-none" id="s_test" style="width:150px;">
                            <option></option>
                            {% for field in field_list %}
                                <option value="{{ field }}">{{ field }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <input type="button" class="form-contral" value="chkOn" id="chkon" style="margin-left:5px;">
                    </div>
                    <div class="form-group">
                        <input type="button" class="form-contral" value="chkOff" id="chkoff" style="margin-left:5px;">
                    </div>

                    <div class="form-group">
                        <input type="button" class="form-contral" value="印刷表示" id="print" style="margin-left:10px;">
                    </div>
                    <div class="form-group" style="margin-left:50px;">
                        <label for="formControlRange" class="d-print-none">サイズ</label>
                        <input type="range" class="form-control-range d-print-none" id="formControlRange">
                    </div>
                    <div class="form-group" style="margin-left:10px;">
                        <label for="txtSize" class="d-print-none">サイズ</label>
                        <input type="text" class="form-control d-print-none" id="txtSize" value="800">
                    </div>

                </form>

            </div>
        </div>
        <!-- 印刷リスト -->
        <div class="row" style="margin-top:10px;">
            <table id="printlist" class="table table-border">

            </table>
        </div>
    </div>

    <div class="row" style="margin-top:10px;">
        <div class="col">
            <p id="t_id"></p>
        </div>
    </div>

    <div class="row" style="margin-top:10px;">
        <div id="qtable">

        </div>
    </div>
{% csrf_token %}
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'bk/js/n22.js' %}"></script>
{% endblock %}

bk/templates/bk/n23.html
{% extends 'bkbase.html' %}
{% load static %}

{% block addhead %}
<style type="text/css">
@media print{
    #header { display:none; }
}
</style>
{% endblock %}

{% block main %}
    <div id="header">
        <h1>日商簿記２級</h1>
        <div class="container-fluid">
            <div class="row" style="margin-top:20px;margin-bottom:20px">
                <div class="col-1"><a href="{% url 'bk:n21' %}" class="btn btn-primary" role="button">問１</a></div>

                <div class="col-1"><a href="{% url 'bk:n22' %}" class="btn btn-primary" role="button">問２</a></div>
                <div class="col-1"><a href="#" class="btn btn-success" role="button">問３</a></div>
                <div class="col-1"><a href="{% url 'bk:n24' %}" class="btn btn-primary" role="button">問４</a></div>
                <div class="col-1"><a href="{% url 'bk:n25' %}" class="btn btn-primary" role="button">問５</a></div>
        </div>
        </div>
        <div class="row">
            <div class="col">
                <form class="form-inline">
                    <div class="form-group">
                        分野選択：
                        <select class="form-control d-print-none" id="s_test" style="width:150px;">
                            <option></option>
                            {% for field in field_list %}
                                <option value="{{ field }}">{{ field }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <input type="button" class="form-contral" value="chkOn" id="chkon" style="margin-left:5px;">
                    </div>
                    <div class="form-group">
                        <input type="button" class="form-contral" value="chkOff" id="chkoff" style="margin-left:5px;">
                    </div>
                    <div class="form-group">
                        <input type="button" class="form-contral" value="印刷表示" id="print" style="margin-left:10px;">
                    </div>
                    <div class="form-group" style="margin-left:50px;">
                        <label for="formControlRange" class="d-print-none">サイズ</label>
                        <input type="range" class="form-control-range d-print-none" id="formControlRange">
                    </div>
                    <div class="form-group" style="margin-left:10px;">
                        <label for="txtSize" class="d-print-none">サイズ</label>
                        <input type="text" class="form-control d-print-none" id="txtSize" value="800">
                    </div>

                </form>

            </div>
        </div>
        <!-- 印刷リスト -->
        <div class="row" style="margin-top:10px;">
            <table id="printlist" class="table table-border">

            </table>
        </div>
    </div>

    <div class="row" style="margin-top:10px;">
        <div class="col">
            <p id="t_id"></p>
        </div>
    </div>

    <div class="row" style="margin-top:10px;">
        <div id="qtable">

        </div>
    </div>
{% csrf_token %}
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'bk/js/n23.js' %}"></script>
{% endblock %}

bk/templates/bk/n24.html
{% extends 'bkbase.html' %}
{% load static %}

{% block addhead %}
<style type="text/css">
@media print{
    #header { display:none; }
}
</style>
{% endblock %}

{% block main %}
    <div id="header">
        <h1>日商簿記２級</h1>
        <div class="container-fluid">
            <div class="row" style="margin-top:20px;margin-bottom:20px">
                <div class="col-1"><a href="{% url 'bk:n21' %}" class="btn btn-primary" role="button">問１</a></div>
                <div class="col-1"><a href="{% url 'bk:n22' %}" class="btn btn-primary" role="button">問２</a></div>
                <div class="col-1"><a href="{% url 'bk:n23' %}" class="btn btn-primary" role="button">問３</a></div>
                <div class="col-1"><a href="#" class="btn btn-success" role="button">問４</a></div>
                <div class="col-1"><a href="{% url 'bk:n25' %}" class="btn btn-primary" role="button">問５</a></div>
        </div>
        </div>
        <div class="row">
            <div class="col">
                <form class="form-inline">
                    <div class="form-group">
                        分野選択：
                        <select class="form-control d-print-none" id="s_test" style="width:150px;">
                            <option></option>
                            {% for field in field_list %}
                                <option value="{{ field }}">{{ field }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <input type="button" class="form-contral" value="chkOn" id="chkon" style="margin-left:5px;">
                    </div>
                    <div class="form-group">
                        <input type="button" class="form-contral" value="chkOff" id="chkoff" style="margin-left:5px;">
                    </div>

                    <div class="form-group">
                        <input type="button" class="form-contral" value="印刷表示" id="print" style="margin-left:10px;">
                    </div>
                    <div class="form-group" style="margin-left:50px;">
                        <label for="formControlRange" class="d-print-none">サイズ</label>
                        <input type="range" class="form-control-range d-print-none" id="formControlRange">
                    </div>
                    <div class="form-group" style="margin-left:10px;">
                        <label for="txtSize" class="d-print-none">サイズ</label>
                        <input type="text" class="form-control d-print-none" id="txtSize" value="800">
                    </div>

                </form>

            </div>
        </div>
        <!-- 印刷リスト -->
        <div class="row" style="margin-top:10px;">
            <table id="printlist" class="table table-border">

            </table>
        </div>
    </div>

    <div class="row" style="margin-top:10px;">
        <div class="col">
            <p id="t_id"></p>
        </div>
    </div>

    <div class="row" style="margin-top:10px;">
        <div id="qtable">

        </div>
    </div>
{% csrf_token %}
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'bk/js/n24.js' %}"></script>
{% endblock %}