bk/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "bk"

urlpatterns = [
    #url(r'^$',views.Index.index , name="index" ),
    url(r'^$',views.Mainpage.mainpage,name="mainpage"),
    url(r'^n21/$',views.N21.n21 , name="n21" ),
    url(r'^ajax_n21_gettimes/$', views.N21.ajax_n21_gettimes, name="ajax_n21_gettimes"),
    url(r'^ajax_n21_getquestion/$',views.N21.ajax_n21_getquestion,name="ajax_n21_getquestion"),

    url(r'^n22/$', views.N22.n22, name="n22"),
    url(r'^ajax_n22_gettimes/$', views.N22.ajax_n22_gettimes, name="ajax_n22_gettimes"),
    url(r'^ajax_n22_getquestion/$', views.N22.ajax_n22_getquestion, name="ajax_n22_getquestion"),

    url(r'^n23/$', views.N23.n23, name="n23"),
    url(r'^ajax_n23_gettimes/$', views.N23.ajax_n23_gettimes, name="ajax_n23_gettimes"),
    url(r'^ajax_n23_getquestion/$', views.N23.ajax_n23_getquestion, name="ajax_n23_getquestion"),

    url(r'^n24/$', views.N24.n24, name="n24"),
    url(r'^ajax_n24_gettimes/$', views.N24.ajax_n24_gettimes, name="ajax_n24_gettimes"),
    url(r'^ajax_n24_getquestion/$', views.N24.ajax_n24_getquestion, name="ajax_n24_getquestion"),

    url(r'^n25/$', views.N25.n25, name="n25"),
    url(r'^ajax_n25_gettimes/$', views.N25.ajax_n25_gettimes, name="ajax_n25_gettimes"),
    url(r'^ajax_n25_getquestion/$', views.N25.ajax_n25_getquestion, name="ajax_n25_getquestion"),

    url(r'^n21cbt/$', views.N21CBT.n21cbt, name="n21cbt"),
    url(r'^ajax_n21cbt_gettimes/$', views.N21CBT.ajax_n21cbt_gettimes, name="ajax_n21cbt_gettimes"),
    url(r'^ajax_n21cbt_getquestion/$', views.N21CBT.ajax_n21cbt_getquestion, name="ajax_n21cbt_getquestion"),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

exam/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "exam"

urlpatterns = [
    url(r'^$',views.Index.index , name="index" ),
    url(r'^admin/',admin.site.urls),
    #MainPage メインページ
    url(r'^mainpage/$', views.MainPage.mainpage, name='mainpage'),
    # Addlicense
    url(r'^addlicense/$', views.Addlicense.addlicense, name='addlicense'),
    # AddlicenseConf
    url(r'^addlicense_conf/$', views.AddlicenseConf.addlicense_conf, name='addlicense_conf'),
    # Inquiry
    url(r'^inquiry/$', views.Inquiry.inquiry, name='inquiry'),
    # Logoff
    url(r'^logoff/$',views.Logoff.logoff,name="logoff"),
    # NewUser
    url(r'^newuser/$', views.NewUser.newuser, name='newuser'),
    # OrgRegister
    url(r'^orgregister/$',views.OrgRegister.orgregister,name='orgregister'),
    # PassChange
    url(r'^passchange/$',views.PassChange.passchange,name='passchange'),
    # PassChangeFinish
    url(r'^passchange_finish',views.PassChangeFinish.passchange_finish,name='passchange_finish'),
    # UserRegisterCsv
    url(r'^userregistercsv/$', views.UserRegisterCsv.userregistercsv, name='userregistercsv'),
    # UserRegisterWeb
    url(r'^userregisterweb/$', views.UserRegisterWeb.userregisterweb, name='userregisterweb'),
    # SaLogin
    url(r'^salogin/$',views.SaLogin.salogin,name='salogin'),
    # SaPage
    url(r'^sapage/$',views.SaPage.sapage,name='sapage'),
    # SaAddlicense
    url(r'^saaddlicense/$',views.SaAddlicense.saaddlicense,name='saaddlicense'),
    # SaAddlicenseFilter
    url(r'^saaddlicense_filter/$',views.SaAddlicenseFilter.saaddlicense_filter,name='saaddlicense_filter'),
    #SaAddlicenseConf
    url(r'^saaddlicense_conf/$',views.SaAddlicenseConf.saaddlicense_conf,name='saaddlicense_conf'),
    # QuestionAmUpLoad
    url(r'^question_am_upload/$',views.QuestioinAmUpload.question_am_upload,name='question_am_upload'),

]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

examsite/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^exam/',include( 'exam.urls')),
    url(r'^jg/', include('jg.urls')),
    url(r'^bk/', include('bk.urls')),
    url(r'^jk/', include('jk.urls')),
    url(r'^ip/',include('ip.urls')),
    url(r'^manager/',include('manager.urls')),
]

jg/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "jg"

urlpatterns = [
    #url(r'^$',views.Index.index , name="index" ),
    url(r'^mainpage/$',views.MainPage.mainpage,name="mainpage"),
    url(r'^mainpage_ajax_getperiod/$', views.MainPage.mainpage_ajax_getperiod, name='mainpage_ajax_getperiod'),
    url(r'^ajax_getquestion_period/$', views.MainPage.ajax_getquestion_period, name='ajax_getquestion_period'),
    url(r'^ajax_getquestion_classify/$', views.MainPage.ajax_getquestion_classify, name='ajax_getquestion_classify'),

    # TestMake　テストを作る
    url(r'^testmake/$', views.TestMake.testmake, name='testmake'),
    url(r'^ajax_getclass/$', views.TestMake.ajax_getclass, name='ajax_getclass'),
    url(r'^ajax_getquestion/$', views.TestMake.ajax_getquestion, name='ajax_getquestion'),
    url(r'^ajax_testupdate/$', views.TestMake.ajax_testupdate, name='ajax_testupdate'),

    # TestMakePeriod　年度期ごとにテストを作る
    url(r'^testmakeperiod/$', views.TestMakePeriod.testmakeperiod, name='testmakeperiod'),
    url(r'^ajax_getperiod/$', views.TestMakePeriod.ajax_getperiod, name='ajax_getperiod'),
    url(r'^ajax_testupdateperiod/$', views.TestMakePeriod.ajax_testupdateperiod, name='ajax_testupdateperiod'),

    # TestDelete テストを削除する
    url(r'^testdelete/$', views.TestDelete.testdelete, name='testdelete'),
    url(r'^ajax_testdelete/$', views.TestDelete.ajax_testdelete, name='ajax_testdelete'),

    # TestPrint　テストを印刷する
    url(r'^testprint/$', views.TestPrint.testprint, name='testprint'),
    url(r'^ajax_gettestprint/$', views.TestPrint.ajax_gettestprint, name='ajax_gettestprint'),

    # AnswerUpload 解答用紙アップロード
    url(r'^answerupload/$', views.AnswerUpload.answerupload, name='answerupload'),
    url(r'^ajax_answerupload/$', views.AnswerUpload.ajax_answerupload, name='ajax_answerupload'),
    url(r'^ajax_answerinsert/$', views.AnswerUpload.ajax_answerinsert, name='ajax_answerinsert'),
    url(r'^ajax_answerallinsert/$', views.AnswerUpload.ajax_answerallinsert, name='ajax_answerallinsert'),
    url(r'^ajax_getanswerlist/$', views.AnswerUpload.ajax_getanswerlist, name='ajax_getanswerlist'),

    # AnswerSheetPrint 解答用紙印刷
    url(r'^answersheetprint/$', views.AnswerSheetPrint.answersheetprint, name='answersheetprint'),
    url(r'^ajax_answersheetprint/$', views.AnswerSheetPrint.ajax_answersheetprint, name='ajax_answersheetprint'),

    # TrainPrint
    url(r'^trainprint/$', views.TrainPrint.trainprint, name='trainprint'),
    url(r'^ajax_gettrainprint/$', views.TrainPrint.ajax_gettrainprint, name='ajax_gettrainprint'),
    url(r'^ajax_testchange/$', views.TrainPrint.ajax_testchange, name='ajax_testchange'),
    url(r'^ajax_m_id_change/$', views.TrainPrint.ajax_m_id_change, name='ajax_m_id_change'),
    url(r'^ajax_s_id_change/$', views.TrainPrint.ajax_s_id_change, name='ajax_s_id_change'),
    url(r'^get_m_list', views.get_m_list, name='get_m_list'),
    url(r'^get_s_list', views.get_m_list, name='get_m_list'),

    # Analysis テストNOごとに結果分析
    url(r'^analysis', views.Analysis.analysis, name='analysis'),
    url(r'^ajax_gettid/$', views.Analysis.ajax_gettid, name='ajax_gettid'),
    url(r'^ajax_getresult/$', views.Analysis.ajax_getresult, name='ajax_getresult'),

    # A_Bunya　分野ごとのテスト結果
    url(r'^a_bunya', views.A_Bunya.a_bunya, name='a_bunya'),
    url(r'^ajax_getresultbunya/$', views.A_Bunya.ajax_getresultbunya, name='ajax_getresultbunya'),

    # A_All　すべてのテスト結果
    url(r'^a_all', views.A_All.a_all, name='a_all'),
    url(r'^ajax_gettestidlist', views.A_All.ajax_gettestidlist, name='ajax_gettestidlist'),
    url(r'^ajax_gettestidresult', views.A_All.ajax_gettestidresult, name='ajax_gettestidresult'),

    # Miss_Question　間違った問題のみ印刷
    url(r'^miss_question/$', views.Miss_Question.miss_question, name='miss_question'),
    url(r'^ajax_miss_question/$', views.Miss_Question.ajax_miss_question, name='ajax_miss_question'),

    # Question_Pm　午後問題
    url(r'^questionpm/$', views.Question_Pm.questionpm, name='questionpm'),
    url(r'^ajax_getquestionpm/$', views.Question_Pm.ajax_getquestionpm, name='ajax_questionpm'),

    # QuestionPmFrame
    url(r'^questionpmframe/$', views.QuestionPmFrame.questionpmframe, name='questionpmframe'),

    # cbt
    url(r'^cbtammain/$', views.CbtAmMain.cbtammain, name='cbtammain'),
    url(r'^cbtam/$', views.CbtAm.cbtam, name='cbtam'),
    url(r'^cbtamresult/$', views.CbtAmResult.cbtamresult, name='cbtamresult'),
    url(r'^cbtpmmain/$', views.CbtPmMain.cbtpmmain, name='cbtpmmain'),
    url(r'^cbtpm/$', views.CbtPm.cbtpm, name='cbtpm'),
    url(r'^cbtpmresult/$', views.CbtPmResult.cbtpmresult, name='cbtpmresult'),
    url(r'^cbtpmresultshow/$', views.CbtPmResultShow.cbtpmresultshow, name='cbtpmresultshow'),
    url(r'^ajax_cbtpm_delete/$',views.CbtPmResultShow.ajax_cbtpm_delete,name='ajax_cbtpm_delete'),
    url(r'^ajax_cbtpm_update/$', views.CbtPm.ajax_cbtpm_update, name='ajax_cbtpm_update'),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

jg/templates/jgbase.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}base{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <!--
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block addhead %}{% endblock %}
    <style type="text/css">
    nav {
        margin-bottom : 10px;
    }
    {% block css %}{% endblock %}
    </style>
</head>
<body>
{% block body %}
<div class="container">
{% block container %}
    {% block nav %}
    {% if u_admin == 1 %}
    <div class="row">
        <div class="col-md-12">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">国家試験対策</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="Navber">
                <ul class="navbar-nav mr-auto">
                    <!--メインページ-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'exam:mainpage' %}">メインページ</a>
                    </li>
                    <!--テスト作成-->
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">テスト作成</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                            <a class="dropdown-item" href="{% url 'jg:testmake' %}">テスト作成</a>
                            <a class="dropdown-item" href="{% url 'jg:testmakeperiod' %}">テスト作成(年度期)</a>
                            <a class="dropdown-item" href="{% url 'jg:testdelete' %}">テストを削除する</a>
                        </div>
                    </li>
                    <!--テスト印刷-->
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">テスト印刷</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                            <a class="dropdown-item" href="{% url 'jg:testprint' %}">テスト印刷</a>
                            <a class="dropdown-item" href="{% url 'jg:answersheetprint' %}">解答用紙印刷</a>
                            <a class="dropdown-item" href="{% url 'jg:trainprint' %}">練習問題</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'jg:answerupload' %}">解答アップロード</a>
                    </li>
                    <!--結果分析-->
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">結果分析</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                            <a class="dropdown-item" href="{% url 'jg:analysis' %}">テストごと</a>
                            <a class="dropdown-item" href="{% url 'jg:a_bunya' %}">分野ごと</a>
                            <a class="dropdown-item" href="{% url 'jg:a_all' %}">全員分</a>
                            <a class="dropdown-item" href="{% url 'jg:miss_question' %}">間違い問題表示</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'jg:questionpm' %}">午後問題印刷</a>
                    </li>
                    <!--CBT試験-->
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">CBT試験</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                            <a class="dropdown-item" href="{% url 'jg:cbtammain' %}">午前試験</a>
                            <a class="dropdown-item" href="{% url 'jg:cbtpmmain' %}">午後試験</a>
                        </div>
                    </li>


                </ul>
                <ul class="navbar-nav my-2 my-lg-0">
                    <li class="nav-link">
                        <a class="nav-link" href="{% url 'exam:logoff' %}">ログオフ</a>
                    </li>
                </ul>
            </div>
        </nav>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-md-12">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">国家試験対策</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="Navber">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'exam:mainpage' %}">メインページ</a>
                    </li>                 
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">【一般】結果</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'jg:analysis' %}">【一般】テストごと</a>
                            <a class="dropdown-item" href="{% url 'jg:a_bunya' %}">【一般】分野ごと</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'jg:questionpm' %}">午後問題印刷</a>
                    </li>
                    <!--CBT試験-->
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">CBT試験</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                            <a class="dropdown-item" href="{% url 'jg:cbtammain' %}">午前試験</a>
                            <a class="dropdown-item" href="{% url 'jg:cbtpmmain' %}">午後試験</a>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav my-2 my-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'exam:logoff' %}">ログオフ</a>
                    </li>
                </ul>
            </div>
        </nav>
        </div>
    </div>
    {% endif %}
    {% endblock %}
    {% block main %}
    {% endblock %}
    
{% endblock%}
</div>
{% endblock %}
{% block script %}
{% endblock %}

</body>
</html>