bk/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "bk"

urlpatterns = [
    #url(r'^$',views.Index.index , name="index" ),
    url(r'^$',views.Mainpage.mainpage,name="mainpage"),
    url(r'^n21/$',views.N21.n21 , name="n21" ),
    url(r'^ajax_n21_gettimes/$', views.N21.ajax_n21_gettimes, name="ajax_n21_gettimes"),
    url(r'^ajax_n21_getquestion/$',views.N21.ajax_n21_getquestion,name="ajax_n21_getquestion"),

    url(r'^n22/$', views.N22.n22, name="n22"),
    url(r'^ajax_n22_gettimes/$', views.N22.ajax_n22_gettimes, name="ajax_n22_gettimes"),
    url(r'^ajax_n22_getquestion/$', views.N22.ajax_n22_getquestion, name="ajax_n22_getquestion"),

    url(r'^n23/$', views.N23.n23, name="n23"),
    url(r'^ajax_n23_gettimes/$', views.N23.ajax_n23_gettimes, name="ajax_n23_gettimes"),
    url(r'^ajax_n23_getquestion/$', views.N23.ajax_n23_getquestion, name="ajax_n23_getquestion"),

    url(r'^n24/$', views.N24.n24, name="n24"),
    url(r'^ajax_n24_gettimes/$', views.N24.ajax_n24_gettimes, name="ajax_n24_gettimes"),
    url(r'^ajax_n24_getquestion/$', views.N24.ajax_n24_getquestion, name="ajax_n24_getquestion"),

    url(r'^n25/$', views.N25.n25, name="n25"),
    url(r'^ajax_n25_gettimes/$', views.N25.ajax_n25_gettimes, name="ajax_n25_gettimes"),
    url(r'^ajax_n25_getquestion/$', views.N25.ajax_n25_getquestion, name="ajax_n25_getquestion"),

    url(r'^n21cbt/$', views.N21CBT.n21cbt, name="n21cbt"),
    url(r'^ajax_n21cbt_gettimes/$', views.N21CBT.ajax_n21cbt_gettimes, name="ajax_n21cbt_gettimes"),
    url(r'^ajax_n21cbt_getquestion/$', views.N21CBT.ajax_n21cbt_getquestion, name="ajax_n21cbt_getquestion"),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

exam/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "exam"

urlpatterns = [
    url(r'^$',views.Index.index , name="index" ),
    url(r'^admin/',admin.site.urls),
    #MainPage メインページ
    url(r'^mainpage/$', views.MainPage.mainpage, name='mainpage'),
    # Addlicense
    url(r'^addlicense/$', views.Addlicense.addlicense, name='addlicense'),
    # AddlicenseConf
    url(r'^addlicense_conf/$', views.AddlicenseConf.addlicense_conf, name='addlicense_conf'),
    # Inquiry
    url(r'^inquiry/$', views.Inquiry.inquiry, name='inquiry'),
    # Logoff
    url(r'^logoff/$',views.Logoff.logoff,name="logoff"),
    # NewUser
    url(r'^newuser/$', views.NewUser.newuser, name='newuser'),
    # OrgRegister
    url(r'^orgregister/$',views.OrgRegister.orgregister,name='orgregister'),
    # PassChange
    url(r'^passchange/$',views.PassChange.passchange,name='passchange'),
    # PassChangeFinish
    url(r'^passchange_finish',views.PassChangeFinish.passchange_finish,name='passchange_finish'),
    # UserRegisterCsv
    url(r'^userregistercsv/$', views.UserRegisterCsv.userregistercsv, name='userregistercsv'),
    # UserRegisterWeb
    url(r'^userregisterweb/$', views.UserRegisterWeb.userregisterweb, name='userregisterweb'),
    # SaLogin
    url(r'^salogin/$',views.SaLogin.salogin,name='salogin'),
    # SaPage
    url(r'^sapage/$',views.SaPage.sapage,name='sapage'),
    # SaAddlicense
    url(r'^saaddlicense/$',views.SaAddlicense.saaddlicense,name='saaddlicense'),
    # SaAddlicenseFilter
    url(r'^saaddlicense_filter/$',views.SaAddlicenseFilter.saaddlicense_filter,name='saaddlicense_filter'),
    #SaAddlicenseConf
    url(r'^saaddlicense_conf/$',views.SaAddlicenseConf.saaddlicense_conf,name='saaddlicense_conf'),
    # QuestionAmUpLoad
    url(r'^question_am_upload/$',views.QuestioinAmUpload.question_am_upload,name='question_am_upload'),

]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

examsite/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^exam/',include( 'exam.urls')),
    url(r'^jg/', include('jg.urls')),
    url(r'^bk/', include('bk.urls')),
    url(r'^jk/', include('jk.urls')),
    url(r'^ip/',include('ip.urls')),
    url(r'^manager/',include('manager.urls')),
]

exam/forms.py
from django import forms

class AnswerImageForm( forms.Form ):
    image = forms.ImageField()

exam/views.py
from io import TextIOWrapper
from django.shortcuts import render,HttpResponseRedirect
from django.http import HttpResponse
from django.core.mail import EmailMessage
import re,string,random,datetime,os,csv
from .models import *
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError
from django.urls import reverse
from django.utils import timezone
from .forms import AnswerImageForm
import json,ast
from django.conf import settings
from .logger import log_write

#関数
#ajaxのPOSTデータをDictionaryに変換する
def byteToDic( data ):
    return ast.literal_eval( data.decode() )
#アクセスログに追加する
def addAccessLog(request,a_page,a_state):
    u_id = request.POST["u_id"]
    ipa = request.environ['REMOTE_ADDR']
    alog = AccessLog(u_id=u_id, a_date=datetime.datetime.now(), a_ipa=ipa, a_page=a_page, a_state=a_state)
    alog.save()
#ランダムな文字を作る関数
def randomCharacter(n):
    c = string.ascii_lowercase + string.ascii_uppercase + string.digits
    return ''.join([random.choice(c) for i in range(n)])
#000Xのコードを作成する
def code4( c ):
    if type( c ) is int:
        if c < 10:
            return '000' + str( c )
        elif c < 100:
            return '00' + str( c )
        elif c < 1000:
            return '0' + str( c )
        else:
            return str( c )
    else:
        if len(c) == 1:
            return '000' + c
        elif len(c) == 2:
            return '00' + c
        elif len(c) == 3:
            return '0' + c
        else:
            return c
#認証システム（キーの追加）
def auth_add(auth_kind,auth_value):
    auth_key = randomCharacter(40)
    auth_date = datetime.datetime.now()
    auth = Auth(auth_key,auth_kind,auth_value,auth_date)
    auth.save()
    return auth_key
#ブルートフォースをチェックする
def checkBruteforce(u_id,a_page):
    delta = datetime.datetime.now() - datetime.timedelta(minutes=10)
    alogs = AccessLog.objects.filter(u_id=u_id,a_page=a_page,a_date__gt=delta)
    if alogs.count() >= 100:
        #攻撃されている
        return True
    else:
        #攻撃されていない
        return False

#セッションにu_idを含むかをチェックする
def securecheck( request ):
    if 'u_id' not in request.session:
        return render( request,'exam/errorpage.html',{'message','不正なアクセスです。'})
#HttpResponseのJSON
def HttpResponseJson( jsonobj ):
    jsonStr = json.dumps( jsonobj , ensure_ascii=False, indent=2)
    return HttpResponse(jsonStr, content_type='application/json', charset='utf-8')

#-*-*-*-*-*-ページ-*-*-*-*-*-*-*-*-*
#ログイン
class Index():
    def index( request):
        request.session.clear()
        return render(request, 'exam/index.html')

#新規ユーザ登録
class NewUser():
    def newuser( request ):
        if request.method != "POST":
            return render(request,'exam/newuser.html')

        u_email = request.POST['u_email']
        # メールアドレスチェック
        #try:
        #    user = User.objects.get(u_email=u_email)
        #except ObjectDoesNotExist:
        #存在しないので登録できる
        auth_key = auth_add('newuser', u_email)

        sub = '新規ユーザ登録'
        con = """
            新規ユーザ登録をしていただきありがとうございました。
            24時間以内に、下記URLから本登録にお進みください。
            http://examsite.room.kaikei.ac.jp/exam/orgregister/?auth_key=%s
            """ % (auth_key)
        EmailMessage(sub, con, to=[u_email, ]).send()
        return render(request, 'exam/message.html', {'message': 'メールアドレス宛に登録サイトのURLを送信しました。'})

        #メールアドレスが存在したので登録できない
        #return render( request,'exam/newuser.html',{'message':'そのメールアドレスはすでに登録されています。'})

#アカウント登録
class OrgRegister():
    def orgregister( request ):
        #入力フォームを取得するリクエスト
        if request.method != "POST":
            auth_key = request.GET['auth_key']
            try:
                Auth.objects.get(pk=auth_key)
                return render( request,'exam/orgregister.html',{'auth_key':auth_key})
            except:
                return render( request,'exam/message.html',{'message':'不正なアクセス'})

        #登録用のリクエスト
        auth_key = request.POST['auth_key']
        u_email = request.POST['u_email']
        try:
            auth = Auth.objects.get(pk=auth_key)
        except ObjectDoesNotExist:
            return render(request, 'exam/newuser.html', {'message': '有効期限が切れました'})

        #時間チェック
        if auth.auth_date_check() != True:
            auth.delete()
            return render( request,'exam/orgregister.html',{'auth_key':auth_key,'message':'有効期限が切れました'})
        #メールアドレスチェック
        if auth.auth_value != u_email:
            return render( request,'exam/orgregister.html',{'auth_key':auth_key,'message':'メールアドレスが違います。'})

        u_id = request.POST['u_id']
        u_pass = request.POST['u_pass']
        o_name = request.POST['o_name']
        u_name = request.POST['u_name']

        num = Org.objects.values('o_id')

        numlist=[]
        for n in num:
            numlist.append( int(n['o_id']) )

        if len( numlist ) == 0:
            o_id = '0001'
        else:
            o_id = code4(max(numlist) + 1)

        org = Org(o_id=o_id,o_name=o_name,l_num=1)
        org.save()

        org = Org.objects.get(o_id=o_id)
        #メディアディレクトリを作成する
        media_dir = os.path.join( settings.STATIC_ROOT ,"exam","answer",o_id)
        #media_dir = "static/exam/answer/" + o_id

        os.mkdir( media_dir )

        try:
            org.user_set.create(u_id=u_id,u_pass=u_pass,u_name=u_name,u_email=u_email,u_admin=1,u_enable=1,u_hidden=0,u_date=datetime.datetime.now())
        except IntegrityError:
            return render( request,'exam/orgregister.html',{'auth_key':auth_key,'message':'そのユーザIDはすでに存在しています。'})
        #不要な認証キーの削除
        auth.delete()
        return HttpResponseRedirect('/exam/')

# パスワードを変更する
class PassChange():
    def passchange( request ):
        return render( request, 'exam/passchange.html')

# パスワードの変更完了
class PassChangeFinish():
    def passchange_finish( request):
        u_id = request.session['u_id']
        old_pass = request.POST['old_pass']
        new_pass = request.POST['new_pass1']
        user = User.objects.get(pk=u_id)
        #print( user.u_pass )
        if old_pass == user.u_pass:
            #print('パスワード変更')
            user.u_pass = new_pass
            user.save()
            return render(request, 'exam/passchange_finish.html',{'message':'パスワードの変更ができました。'})
        else:
            #print('パスワードが違う')
            return render(request, 'exam/passchange.html',{'message':'パスワードが違うので変更できません。'})

#管理者問い合わせ
class Inquiry():
    def inquiry( request ):
        #POSTでない
        if request.method!='POST':
            return render( request,'exam/inquiry.html')
        #POST送信
        if "lock_u_id" in request.POST :
            u_id = request.POST["lock_u_id"]
            u_pass = request.POST["lock_u_pass"]
            user = User.objects.get(pk=u_id)
            #ブルートフォース検出
            if checkBruteforce(u_id,'inquiry'):
                user.u_enable = 0
                user.save()
                con = """
                不正なアクセスを検知したので、アカウントをロックしました。
                解除申請をしてください。
                """
                EmailMessage('アカウントロック', con, to=[user.u_email, ]).send()
                return render(request,'exam/errorpage.html',{'message':'不正なログインを検知しました。アカウントをロックします。'})

            # パスワードが一致
            if user.u_pass == u_pass:
                user.u_enable = 1
                user.save()
                addAccessLog(request, 'inquiry', 's')
                return render( request,'exam/index.html')
            else:
                addAccessLog(request,'inquiry','f')
                return render(request,'exam/errorpage.html',{'message':'解除できません'})

        #パスワードのリセット
        if 'pass_u_id' in request.POST:
            u_id = request.POST['pass_u_id']
            u_email = request.POST['pass_u_email']
            try:
                user = User.objects.get(pk=u_id)
            except:
                return render( request,'exam/errorpage.html',{'message':'ユーザIDとメールアドレスが一致しません。'})

            if user.u_email == u_email:
                #except:
                    #メールアドレスが存在しない
                #    return errorpage(request,'メールアドレスが存在しません。')

                #仮パスワードの設定
                damypass = randomCharacter(10)
                user.u_pass = damypass
                user.save()
                con = """
                仮のパスワードを設定しました。
                【仮パスワード】%s
               ログイン後変更してください。
                """%damypass
                EmailMessage('仮パスワードの設定',con,to=[u_email,]).send()
                content = "仮パスワードを設定しました。登録メールアドレスに仮パスワードを送りましたので、確認してください。"
                return render( request,'exam/message.html',{'message':content})

            return render( request,'exam/errorpage.html',{'message':'ユーザIDとメールアドレスが一致しません。'})

        if 'fgid_u_email' in request.POST:
            u_email = request.POST['fgid_u_email']

            try:
                user = User.objects.get(u_email=u_email)
            except:
                return render( request,'exam/errorpage.html',{'message':'登録されていないメールアドレスです。'})

            u_id = user.u_id

            con = """
            ユーザIDは
            %s
            です。
            """%u_id

            EmailMessage('ユーザID',con,to=[u_email,]).send()

            return render( request,'exam/message.html',{'message':'登録されているメールアドレスにユーザIDをお送りしました。'})

#ライセンスの購入
class Addlicense():
    def addlicense( request ):
        #セッションにユーザIDの記録がない
        securecheck( request )

        o_id = request.session['o_id']
        org = Org.objects.get(o_id=o_id)
        o_name = org.o_name
        return render( request,'exam/addlicense.html',{'o_id':o_id,'o_name':o_name,'u_admin':request.session['u_admin']})

#ライセンスの購入
class AddlicenseConf():
    def addlicense_conf( request ):
        message = """
        購入処理をしております。
        終わりましたら、登録のメールアドレスにご連絡いたします。
        しばらくお待ちください。
        """
        o_id = request.POST['o_id']
        l_num = request.POST['l_num']

        adr = AddLicenseRequest(o_id=o_id,l_num=l_num,check=False,adr_date=datetime.datetime.now())
        adr.save()

exam/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}base{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <!--
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block addhead %}{% endblock %}
    <style type="text/css">
    nav {
        margin-bottom : 10px;
    }
    {% block css %}{% endblock %}
    </style>
</head>
<body>
{% block body %}
<div class="container">
{% block container %}
    {% block nav %}
    {% if u_admin == 1 %}
    <div class="row">
        <div class="col-md-12">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">検定システムサイト</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="Navber">
                <ul class="navbar-nav mr-auto">
                    <!--メインページ-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'exam:mainpage' %}">メインページ</a>
                    </li>
                    <!--管理者メニュー-->
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">管理者メニュー</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                            <a class="dropdown-item" href="{% url 'exam:addlicense' %}">ライセンスの追加</a>
                            <a class="dropdown-item" href="#">ユーザの有効期限を延長</a>
                            <a class="dropdown-item" href="{% url 'exam:userregistercsv' %}">ユーザの追加(csv)</a>
                            <a class="dropdown-item" href="{% url 'exam:userregisterweb' %}">ユーザの追加(web)</a>
                            <a class="dropdown-item" href="{% url 'exam:question_am_upload' %}">午前問題アップロード</a>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav my-2 my-lg-0">
                    <li class="nav-link">
                        <a class="nav-link" href="{% url 'exam:logoff' %}">ログオフ</a>
                    </li>
                </ul>
            </div>
        </nav>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-md-12">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">検定システムサイト</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="Navber">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'exam:mainpage' %}">メインページ</a>
                    </li>
                </ul>
                <ul class="navbar-nav my-2 my-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'exam:logoff' %}">ログオフ</a>
                    </li>
                </ul>
            </div>
        </nav>
        </div>
    </div>
    {% endif %}
    {% endblock %}
    {% block main %}
    {% endblock %}
    
{% endblock%}
</div>
{% endblock %}
{% block script %}
{% endblock %}

</body>
</html>